### ISSUE TITLE
qcluster stuck forever when initial connection failed in ORM broker

### ISSUE THREAD

**Issue by cd-fge** [django-q2/django-q2#201]
When starting qcluster the following happens:

* `Cluster.start()` starts a new process, calls `Sentinel()` in it and waits until Sentinel emits `start_event`
* `Sentinel()` instantiates the broker though `get_broker()`
* The broker `__init__()` calls `get_connection()`

If the connection attempt fails in the ORM broker, `get_connection()` raises an exception.
As a result the Sentinel process dies and the main process waits forever for `start_event`.
There is not indication from the outside (besides the log entries) that the qcluster is permanently non-functional.

The root cause seems to be that `ORM.__init__()` through `get_connection()` actually tries to establish a connection. Redis on the other hand seems to only setup the client without any network connection.
In the best case this is unnecessary overhead. `self.connection` is never used and the constructor is called from the Sentinel process so the pusher process needs to establish a new connection anyway. In the worst case the above happens.

I think ideally `Broker.connection` should be initialized lazily. That would generally reduce the amount of code that is run in the Sentinel process.

**Comment by meshulam** [comment]
I encountered this as well, stack trace from version 1.7.2:

```
Process Process-de62b4a1ffd441d7812b7913e614e147:
Traceback (most recent call last):
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/psycopg/connection.py", line 117, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection is bad: connection to server at "::1", port 5432 failed: Cannot assign requested address
        Is the server running on that host and accepting TCP/IP connections?
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django_q/cluster.py", line 149, in __init__
    self.broker = broker or get_broker()
                            ^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django_q/brokers/__init__.py", line 193, in get_broker
    return orm.ORM(list_key=list_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django_q/brokers/__init__.py", line 13, in __init__
    self.connection = self.get_connection(list_key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django_q/brokers/orm.py", line 20, in get_connection
    if transaction.get_autocommit(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/transaction.py", line 30, in get_autocommit
    return get_connection(using).get_autocommit()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 454, in get_autocommit
    self.ensure_connection()
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/opt/msi/mymsi/venv/lib64/python3.12/site-packages/psycopg/connection.py", line 117, in connect
    raise last_ex.with_traceback(None)
django.db.utils.OperationalError: connection is bad: connection to server at "::1", port 5432 failed: Cannot assign requested address
        Is the server running on that host and accepting TCP/IP connections?
```

I will try upgrading to the latest version but it doesn't seem like any recent changes would address this. I might take a stab at a PR to lazily initiate the connection as OP suggested.
