### ISSUE TITLE
pydoc issue?

### ISSUE THREAD

**Issue by LeoWelter** [django-q2/django-q2#252]
- python 3.11
- django-q2 1.7.4
- django 4.2.11
- django / postgresql backend (low volume tasks)

I encounter the following error:

`
Process-030dcc63e4c74de88f943d44dd62f114 ready for work at 188677
Process-030dcc63e4c74de88f943d44dd62f114 processing single-fourteen-march-social 'None'
Process Process-030dcc63e4c74de88f943d44dd62f114:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/<deleted for privacy>/prod/venv311/lib/python3.11/site-packages/django_q/cluster.py", line 523, in worker
    f = pydoc.locate(f)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pydoc.py", line 1806, in locate
    parts = [part for part in path.split('.') if part]
                              ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
reincarnated worker Process-030dcc63e4c74de88f943d44dd62f114 after death
Process-0908d70ac1fb42d5b5497d1bcfe9b1a8 ready for work at 188738
`
Any ideas what this could be? (it also happened under 1.6.0)

**Comment by GDay** [comment]
How does the task or schedule look like? it looks like it can't find the key you entered. Remember it needs to have a dot notation or be a function directly.
