### ISSUE TITLE
BadSignature error 

### ISSUE THREAD

**Issue by Amanb1145** [django-q2/django-q2#82]
Hey, I am getting this error on one of my servers- 
```
Message: BadSignature('Signature "Oi9T5QQeT9ag7ayHMWlnJ9ifcZ2vE1_TUNDgLnxAbK0" does not match')
Arguments: ('Traceback (most recent call last):\n  File "/home/ubuntu/dev-backend/venv/lib/python3.8/site-packages/django_q/cluster.py", line 356, in pusher\n    task = SignedPackage.loads(task[1])\n  File "/home/ubuntu/dev-backend/venv/lib/python3.8/site-packages/django_q/signing.py", line 25, in loads\n    return signing.loads(\n  File "/home/ubuntu/dev-backend/venv/lib/python3.8/site-packages/django_q/core_signing.py", line 35, in loads\n    base64d = force_bytes(TimestampSigner(key, salt=salt).unsign(s, max_age=max_age))\n  File "/home/ubuntu/de-backend/venv/lib/python3.8/site-packages/django_q/core_signing.py", line 70, in unsign\n    result = super(TimestampSigner, self).unsign(value)\n  File "/home/ubuntu/dev-backend/venv/lib/python3.8/site-packages/django_q/core_signing.py", line 55, in unsign\n    raise BadSignature(\'Signature "%s" does not match\' % sig)\ndjango.core.signing.BadSignature: Signature "Oi9T5QQeT9ag7ayHMWlnJ9ifcZ2vE1_TUNDgLnxAbK0" does not match\n',)
```
any ideas ?

**Comment by Amanb1145** [comment]
fixed it by this- `python -c "import secrets; print(secrets.token_urlsafe())"

`

**Comment by GDay** [comment]
Are you using different `SECRET_KEY`s with your installation (or did you change it after some time)? To pack/unpack packages the `SECRET_KEY` needs to be the same, otherwise it will raise that error. Or did you perhaps change any of the settings (such as `compress`)?

**Comment by Amanb1145** [comment]
Hey, I was running 2 Django projects on server and both were using clusters on same port maybe that is why the error came otherwise I have same project running on a diff server without any error.

**Comment by GDay** [comment]
> were using clusters on same port

Same port?

If you are using the same broker for the two apps and you didn't set a different [name](https://django-q2.readthedocs.io/en/master/configure.html#name), then yeah, that could be the issue.

**Comment by mast3rbow** [comment]
@Amanb1145, I had the same issue. Turns out my Django_q was using the same redis backend, updating the queue names fixed the bad signature error. So I would recommend setting a name.

**Comment by aji-pratama** [comment]
have you fix this problem?

**Comment by gcmestre** [comment]
I had this issue in one of my servers as well.
It was a stupid mistake but it may help someone, so I leave my issue here.
In one of the servers I didn't define `SECRET_KEY `.
On the `setings.py` file I had 

` SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())`

What happened was when I run `python manage.py qcluster` a new SECRET_KEY was generated  for the new instance. 
This was causing the BadSignature error.

Fix:Define a secure SECRET_KEY in the environment
